TetrisGym-v0:
  policy: MultiInputPolicy
  frame_stack: 4
  gamma: 0.99
  n_envs: 8
  n_steps: 128
  n_epochs: 4
  batch_size: 256
  n_timesteps: !!float 1e7
  learning_rate: lin_2.5e-4
  clip_range: lin_0.1
  vf_coef: 0.5
  ent_coef: 0.01
  gae_lambda: 0.95